# Site settings
title: Jeff McAffer
email: jeffmcaffer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jeff McAffer on open source, Microsoft, and maybe even car racing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcaffer.com" # the base hostname & protocol for your site
twitter_username: jeffmcaffer
github_username:  jeffmcaffer

excerpt_separator: <!--more-->

permalink: /:year/:month/:title

# Build settings
markdown: kramdown
highlighter: rouge
